spring:
  profiles:
    active: feign, insecure, cloud

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.nayanzin.edgeservice.zuul.CorsFilter: DEBUG

zuul:
  routes:
    hello:
      serviceId: greetings-service
      path: /lets/**